== flexi-serverless

flexi-serverless is just a simple framework to run the same serverless function either locally (sequential or parallel) or on AWS Lambda for embarrassingly parallel applications.

It is part of my master thesis at University of Vienna, Department of Computer Science.

===  Requirements

* https://developer.hashicorp.com/terraform[Terraform ]
* https://aws.amazon.com/cli/[AWS CLI]
* google cli (gcloud)
* https://docs.docker.com/engine/install/[Docker]


// ===  Local Setup
// [source,bash]
// ----
// ## Setup
// # Copy the example env file and populate missing values
// cp .env.example .env
// ----

=== Deployment & Testing using flexi-serverless

==== 1. Compile client
[source,bash]
----
cd client
make
----

=== Manual Deployment & Testing

If you want to deploy and test the function manually, you can follow the steps below.

==== 1. Create and Deploy Function

Make to create the function handler and Dockerfile in the functions directory where the terraform files are located.

[source,bash]
----
cd terraform/aws
terraform init
terraform plan
terraform apply
----

==== 2. Test Function Locally
[source,bash]
----
cd terraform/aws/functins/functionName
docker build -t docker-image:test .
docker run -p 9000:8080 docker-image:test
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
----

==== 3. Test Function on AWS
[source,bash]
----
 aws lambda invoke \
--payload '{"beer": "tasty"}' --function-name example-dev \
--cli-binary-format raw-in-base64-out \
response.json

----

=== Manual Deployment & Testing Examples for Each Function and Client Application

Monte Carlo Simulations

[source,bash]
----
cd terraform/aws/functins/montecarlo
docker build -t docker-image:montecarlo .
docker run -p 9000:8080 docker-image:montercarlo
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '[{"id": 1, "iterations": 1000, "lowBound": 0, "upBound": 10}, {"id": 2, "iterations": 2000, "lowBound": 5, "upBound": 15}]' -H "Content-Type: application/json"

aws lambda invoke \
--payload '[{"id": 1, "iterations": 1000, "lowBound": 0, "upBound": 10}, {"id": 2, "iterations": 2000, "lowBound": 5, "upBound": 15}]' \
--function-name montecarlo-dev \
--cli-binary-format raw-in-base64-out \
response.json
cat response.json

export FLEXI_PROVIDER=AWS
cd application/monte-carlo-simulations
./build-flex.sh
./build.sh
./build-local.sh
./main [threads] [totalInvocations] [iterations]
./mainlocal [threads] [totalInvocations] [iterations]


----

Image Filtering

[source,bash]
----
cd terraform/aws/functins/imagefiltering
npm i
docker build -t docker-image:imagefiltering .
docker run -p 9000:8080 docker-image:imagefiltering
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"imagePairs":[{"id":1,"imageUrl":"https://i.etsystatic.com/37370207/r/il/8322f3/5483389650/il_1588xN.5483389650_7hvp.jpg"},{"id":2,"imageUrl":"https://i.etsystatic.com/37370207/r/il/8322f3/5483389650/il_1588xN.5483389650_7hvp.jpg"}]}' -H "Content-Type: application/json"

aws lambda invoke \
--payload '{"imagePairs":[{"id":1,"imageUrl":"https://i.etsystatic.com/37370207/r/il/8322f3/5483389650/il_1588xN.5483389650_7hvp.jpg"},{"id":2,"imageUrl":"https://i.etsystatic.com/37370207/r/il/8322f3/5483389650/il_1588xN.5483389650_7hvp.jpg"}]}' \
--function-name imagefiltering-dev \
--cli-binary-format raw-in-base64-out \
response.json


export FLEXI_PROVIDER=AWS
cd application/image-filtering
./build-flex.sh
./build.sh
./build-local.sh
./main.out <filename> [threads] [totalInvocations] [imagesPerInvocation]
./mainlocal <filename> [threads] [totalInvocations] [imagesPerInvocation]

e.g.
./main 2 4 2
./mainlocal 2 4 2
----

String Similarity

[source,bash]
----
cd terraform/aws/functins/stringsimilarity
docker build -t docker-image:stringsimilarity .
docker run -p 9000:8080 docker-image:stringsimilarity
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '[{"id":1,"str1":"hello","str2":"world"},{"id":2,"str1":"foo","str2":"bar"}]' -H "Content-Type: application/json"

aws lambda invoke \
--payload '[{"id":1,"str1":"hello","str2":"world"},{"id":2,"str1":"foo","str2":"bar"}]' \
--function-name stringsimilarity-dev \
--cli-binary-format raw-in-base64-out \
response.json

export FLEXI_PROVIDER=AWS
cd application/string-similarity
./build-flex.sh
./build.sh
./build-local.sh
./main <filename> [threads] [pairs_per_invocation]
./mainlocal <filename> [threads] [pairs_per_invocation]

e.g.  ./main.out strings.txt 2 2


----

